In [18]:
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
df = pd.read_excel("./data/시도별_전출입_인구수.xlsx")
df.head(0)

Empty DataFrame
Columns: [전출지별, 전입지별, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Index: []

[0 rows x 50 columns]

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    19 non-null     str
 1   전입지별    325 non-null    str
 2   1970    325 non-null    object
 3   1971    325 non-null    object
 4   1972    325 non-null    object
 5   1973    325 non-null    object
 6   1974    325 non-null    object
 7   1975    325 non-null    object
 8   1976    325 non-null    object
 9   1977    325 non-null    object
 10  1978    325 non-null    object
 11  1979    325 non-null    object
 12  1980    325 non-null    object
 13  1981    325 non-null    object
 14  1982    325 non-null    object
 15  1983    325 non-null    object
 16  1984    325 non-null    object
 17  1985    325 non-null    object
 18  1986    325 non-null    object
 19  1987    325 non-null    object
 20  1988    325 non-null    object
 21  1989    325 non-null    object
 22  1990    325 non-null    object
 23  1991    325 non-null    object
 24  1992    325 non-null    object
 25  1993    325 non-null    object
 26  1994    325 non-null    object
 27  1995    325 non-null    object
 28  1996    325 non-null    object
 29  1997    325 non-null    object
 30  1998    325 non-null    object
 31  1999    325 non-null    object
 32  2000    325 non-null    object
 33  2001    325 non-null    object
 34  2002    325 non-null    object
 35  2003    325 non-null    object
 36  2004    325 non-null    object
 37  2005    325 non-null    object
 38  2006    325 non-null    object
 39  2007    325 non-null    object
 40  2008    325 non-null    object
 41  2009    325 non-null    object
 42  2010    325 non-null    object
 43  2011    325 non-null    object
 44  2012    325 non-null    object
 45  2013    325 non-null    object
 46  2014    325 non-null    object
 47  2015    325 non-null    object
 48  2016    325 non-null    object
 49  2017    325 non-null    object
dtypes: object(48), str(2)
memory usage: 127.1+ KB

In [21]:
df = df.ffill()
df.head()

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,전국,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,전국,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,전국,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    325 non-null    str
 1   전입지별    325 non-null    str
 2   1970    325 non-null    object
 3   1971    325 non-null    object
 4   1972    325 non-null    object
 5   1973    325 non-null    object
 6   1974    325 non-null    object
 7   1975    325 non-null    object
 8   1976    325 non-null    object
 9   1977    325 non-null    object
 10  1978    325 non-null    object
 11  1979    325 non-null    object
 12  1980    325 non-null    object
 13  1981    325 non-null    object
 14  1982    325 non-null    object
 15  1983    325 non-null    object
 16  1984    325 non-null    object
 17  1985    325 non-null    object
 18  1986    325 non-null    object
 19  1987    325 non-null    object
 20  1988    325 non-null    object
 21  1989    325 non-null    object
 22  1990    325 non-null    object
 23  1991    325 non-null    object
 24  1992    325 non-null    object
 25  1993    325 non-null    object
 26  1994    325 non-null    object
 27  1995    325 non-null    object
 28  1996    325 non-null    object
 29  1997    325 non-null    object
 30  1998    325 non-null    object
 31  1999    325 non-null    object
 32  2000    325 non-null    object
 33  2001    325 non-null    object
 34  2002    325 non-null    object
 35  2003    325 non-null    object
 36  2004    325 non-null    object
 37  2005    325 non-null    object
 38  2006    325 non-null    object
 39  2007    325 non-null    object
 40  2008    325 non-null    object
 41  2009    325 non-null    object
 42  2010    325 non-null    object
 43  2011    325 non-null    object
 44  2012    325 non-null    object
 45  2013    325 non-null    object
 46  2014    325 non-null    object
 47  2015    325 non-null    object
 48  2016    325 non-null    object
 49  2017    325 non-null    object
dtypes: object(48), str(2)
memory usage: 127.1+ KB

In [23]:
mask = (df['전출지별'] == '서울특별시') & (df['전입지별'] != '서울특별시')
df_seoul = df[mask]
df_seoul

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
19,서울특별시,전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,...,2083352,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423
21,서울특별시,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
22,서울특별시,대구광역시,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
23,서울특별시,인천광역시,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
24,서울특별시,광주광역시,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
25,서울특별시,대전광역시,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
26,서울특별시,울산광역시,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
27,서울특별시,세종특별자치시,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
28,서울특별시,경기도,130149,150313,93333,143234,149045,253705,202276,207722,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
29,서울특별시,강원도,9352,12885,13561,16481,15479,27837,25927,25415,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
30,서울특별시,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
31,서울특별시,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
32,서울특별시,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
33,서울특별시,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
34,서울특별시,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
35,서울특별시,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
36,서울특별시,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [24]:
df_seoul = df_seoul.drop(['전출지별'], axis=1)
df_seoul

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
19,전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,3028911,...,2083352,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423
21,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
22,대구광역시,-,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
23,인천광역시,-,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
24,광주광역시,-,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
25,대전광역시,-,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
26,울산광역시,-,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
27,세종특별자치시,-,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
28,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
29,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
30,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
31,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
32,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
33,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
34,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
35,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
36,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [25]:
df_seoul = df_seoul.rename({'전입지별':'전입지'}, axis=1)
df_seoul = df_seoul.set_index('전입지')
df_seoul

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
전입지,,,,,,,,,,,,,,,,,,,,,
전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,3028911,2441242,...,2083352,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423
부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,28542,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
대구광역시,-,-,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
인천광역시,-,-,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
광주광역시,-,-,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
대전광역시,-,-,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
울산광역시,-,-,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
세종특별자치시,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,278411,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,27599,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,20047,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,45388,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,31570,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,47934,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,43565,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,30183,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,4261,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404