In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("./data/auto-mpg.csv", header=None)
df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

df["horsepower"] = df["horsepower"].replace("?", np.nan)
df = df.dropna(subset=["horsepower"])
df["horsepower"] = df["horsepower"].astype("float")

df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   name          392 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 36.8 KB

In [6]:
df["horsepower"].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [8]:
count, bin_dividers = np.histogram(df["horsepower"], bins=3)

In [9]:
bin_names = ["저출력", "보통출력", "고출력"]

df["hp_bin"] = pd.cut(
    x=df["horsepower"], 
    bins=bin_dividers, 
    labels=bin_names, 
    include_lowest=True
)

df[["horsepower", "hp_bin"]].head(15)

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [10]:
# 더미변수
df["hp_bin"]

0      보통출력
1      보통출력
2      보통출력
3      보통출력
4      보통출력
       ...
393     저출력
394     저출력
395     저출력
396     저출력
397     저출력
Name: hp_bin, Length: 392, dtype: category
Categories (3, str): ['저출력' < '보통출력' < '고출력']

In [11]:
bin_names = ["저출력", "보통출력", "고출력"]
df["hp_bin"] = pd.cut(x=df["horsepower"],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)

df[["horsepower", "hp_bin"]].head(3)

   horsepower hp_bin
0       130.0   보통출력
1       165.0   보통출력
2       150.0   보통출력

In [12]:
horsepower_dummies = pd.get_dummies(df["hp_bin"])
print(horsepower_dummies.head(15))

      저출력   보통출력    고출력
0   False   True  False
1   False   True  False
2   False   True  False
3   False   True  False
4   False   True  False
5   False  False   True
6   False  False   True
7   False  False   True
8   False  False   True
9   False  False   True
10  False  False   True
11  False   True  False
12  False   True  False
13  False  False   True
14   True  False  False

In [13]:
horsepower_dummies_float = pd.get_dummies(df["hp_bin"], dtype=float)
horsepower_dummies_float.head()

   저출력  보통출력  고출력
0  0.0   1.0  0.0
1  0.0   1.0  0.0
2  0.0   1.0  0.0
3  0.0   1.0  0.0
4  0.0   1.0  0.0

In [14]:
horsepower_dummies_drop = pd.get_dummies(df["hp_bin"], dtype=float,
                                         drop_first=True)
horsepower_dummies_drop.head()

   보통출력  고출력
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0

In [19]:
# from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df["hp_bin"].head(15))
print(onehot_labeled)
print(type(onehot_labeled))
print(onehot_labeled.ndim)

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>
1

In [23]:
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)

onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>