In [1]:
import pandas as pd

fruit_names = pd.Series(
    ["Apple", "Banana", "Cherry"]
)

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [2]:
fruit_names = pd.Series(
    ["Apple", "Banana", "Cherry"], dtype="string"
)

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: string

In [3]:
import pandas as pd
import numpy as np

ser = pd.Series(
    ["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
    index=["First ", " Second", " Third", "Fourth"]
)

print(ser)
print()

ser2 = pd.Series(
    ["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
    index=["First ", " Second", " Third", "Fourth"],
    dtype = "string"
)

print(ser2)

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth           <NA>
dtype: string

In [4]:
ser.str.lower()

First        apple_사과
 Second    banana_바나나
 Third      cherry_체리
Fourth            NaN
dtype: str

In [5]:
ser.str.upper()

First        APPLE_사과
 Second    BANANA_바나나
 Third      CHERRY_체리
Fourth            NaN
dtype: str

In [6]:
ser

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str

In [7]:
ser.str.len()

First       8.0
 Second    10.0
 Third      9.0
Fourth      NaN
dtype: float64

In [8]:
ser.str.split("_")

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Third      [Cherry, 체리]
Fourth               NaN
dtype: object

In [9]:
ser.str.split("_", expand=True)

              0    1
First     Apple   사과
 Second  Banana  바나나
 Third   Cherry   체리
Fourth      NaN  NaN

In [11]:
ser.str.split("_").str.get(1)

First       사과
 Second    바나나
 Third      체리
Fourth     NaN
dtype: object

In [12]:
ser.index

Index(['First ', ' Second', ' Third', 'Fourth'], dtype='str')

In [14]:
idx = ser.index

In [15]:
idx.str.strip()

Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [16]:
idx.str.rstrip()

Index(['First', ' Second', ' Third', 'Fourth'], dtype='str')

In [17]:
ser.str.replace("_", ":", regex=False)

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: str

In [ ]:
ser.str.replace(r"[^a-zA-Z\s]", "") ##

First        Apple_사과
 Second    Banana_바나나
 Third      Cherry_체리
Fourth            NaN
dtype: str

In [20]:
ser.str[0]

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: str

In [21]:
ser.str[0:4]

First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [22]:
ser.str.contains("A", na=False)

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [23]:
ser.str.contains(r"[A|B][a-z]+")

First       True
 Second     True
 Third     False
Fourth     False
dtype: bool

In [25]:
ser.str.fullmatch(r"[A|B|C][a-z]+_[가-힣]+")

First       True
 Second     True
 Third      True
Fourth     False
dtype: bool

In [8]:
import pandas as pd

dict_data = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

# 1. df 라는 이름의 데이터프레임을 만들어 주세요
df = pd.DataFrame(dict_data)
df

    이름  나이 성별   수학  영어
0  김철수  20  남   90  85
1  이영희  21  여   85  95
2  박민수  22  남   70  75
3  최지우  20  여  100  90

In [9]:
# 2. 생성된 데이터프레임의 상위 2개 행만 출력하세요.
print(df.head(2))

    이름  나이 성별  수학  영어
0  김철수  20  남  90  85
1  이영희  21  여  85  95

In [3]:
# 3. 데이터프레임의 요약 정보(컬럼명, 데이터 타입 )을 확인하세요
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   나이      4 non-null      int64
 2   성별      4 non-null      str
 3   수학      4 non-null      int64
 4   영어      4 non-null      int64
dtypes: int64(3), str(2)
memory usage: 292.0 bytes
None

In [10]:
# 4. '이름' 컬럼을 인덱스로 설정하세요. (기존 df를 수정)
# df.set_index('이름', inplace=True)
df = df.set_index(["이름"])
df

     나이 성별   수학  영어
이름
김철수  20  남   90  85
이영희  21  여   85  95
박민수  22  남   70  75
최지우  20  여  100  90

In [11]:
# 5. loc을 사용하여 '이영희'의 '수학' 점수와 '영어' 점수만 추출하세요.
print(df.loc['이영희', ['수학', '영어']])

수학    85
영어    95
Name: 이영희, dtype: int64

In [13]:
# 6. iloc을 사용하여 첫 번째 행부터 두 번째 행까지, 그리고 2번째 열(수학)부터 마지막 열까지 슬라이싱하세요.
print(df.iloc[0:2, 2:])

     수학  영어
이름
김철수  90  85
이영희  85  95

In [15]:
# 1. 위 데이터로 시리즈 객체 sr을 만들어주세요

dict_data2 = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

sr = pd.Series(dict_data2)
sr

이름    [김철수, 이영희, 박민수, 최지우]
나이        [20, 21, 22, 20]
성별            [남, 여, 남, 여]
수학       [90, 85, 70, 100]
영어        [85, 95, 75, 90]
dtype: object

In [16]:
# 2. 시리즈의 인덱스 배열과 데이터값 배열을 각각 추출하여 화면에 출력하세요.
print(sr.index)
print(sr.values)

Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')
[list(['김철수', '이영희', '박민수', '최지우']) list([20, 21, 22, 20])
 list(['남', '여', '남', '여']) list([90, 85, 70, 100]) list([85, 95, 75, 90])]

In [17]:
# 3. 위 데이터를 시리즈 객체로 만들어 주세요
list_data = ["2010-01-02", 3.14, "ABC", 100, True]
sr = pd.Series(list_data)
sr

0    2010-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [18]:
# 4. 데이터 타입을 출력해보세요
print(type(sr))

<class 'pandas.Series'>

In [ ]:
# 5. 위 데이터를 시리즈객체로 생성해주세요.
tup_data = ("영인", "2010-05-01", "여", True)
index_labels = ["이름", "생년월일", "성별", "학생여부"]

ndf = pd.Series(tup_data, index=index_labels)
ndf

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [ ]:
# 6. 해당 시리즈의 원소 개수, 형상(shape), 차원을 출력해주세요 
print(len(ndf))
print(ndf.shape)
print(ndf.ndim)

4
(4,)
1

In [21]:
# 7. 위치 기반(정수)으로 첫 번째 원소를 안전하게 조회하는 코드를 작성하세요. (iloc 활용)
print(ndf.iloc[0])

영인

In [25]:
# 8. 라벨 '이름'으로 원소를 조회하는 코드를 작성하세요.
print(ndf.loc["이름"])

영인

In [23]:
# 9. 위치 인덱스 번호 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요. (iloc 권장)
print(ndf.iloc[1:3])

생년월일    2010-05-01
성별               여
dtype: object

In [24]:
# 10. 라벨 이름 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요.
print(ndf[["생년월일", "성별"]])

생년월일    2010-05-01
성별               여
dtype: object

In [28]:
# 11. 아무 데이터도 전달하지 않은 기본형 빈 시리즈를 생성하세요.
df = pd.Series()
df

Series([], dtype: object)

In [30]:
# 12. 스칼라 값 5와 인덱스 ["a", "b", "c"]를 사용하여 시리즈를 생성하고 출력하세요.
df = pd.Series(5, index=["a", "b", "c"])
print(df)

a    5
b    5
c    5
dtype: int64